### ISSUE TITLE
Breadcrumbs collections and subcollections items 

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#100]
Since we changed the navigation from folders to the table of contents, it seems that collections and subcollections in breadcrumbs don't take you anywhere. 

With the current table of content book view, when we're on the section page and click on a collection or subcollection in the breadcrumbs, it should take us to the book view at that part of the book (like we were clicking on the table of contents).

<img width="587" alt="breadcrumbs-collections-subcol" src="https://github.com/Simple2B/open_law/assets/16442033/d8c25369-a98b-4aae-aa11-d29671c07f69">

**Comment by StoliarskyiKostiantyn** [comment]
Done!
