### ISSUE TITLE
`Sort by` feature

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#103]
Pages:
- home/latestinterpretations
- section page with interpretations (not for interpretation page with comments)
- mycontributions page

Options:
- Most upvoted
- Most recent
- Most comments

Pages:
- home/explorebooks
- favbooks page

Options:
- Most favorited
- Most recent
- Most interpretations

Remove `Sort by` feature for search results for now.

**Comment by StoliarskyiKostiantyn** [comment]
Done! Closed in #137
