### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#106]
On your book
- New interpretation to SectionLabel on BookLabel / 3 new interpretations to SectionLabel on BookLabel
- Actions from contributors
    - Username added a section on BookLabel
    - Username renamed a section on BookLabel
    - Username deleted a section on BookLabel
    - Username approved an interpretation for SectionLabel on BookLabel
    - Username added a collection on BookLabel
    - Username renamed a collection on BookLabel
    - Username deleted a collection on BookLabel
    - Username added a collection on BookLabel

On your interpretation or comment
- New comment to your interpretation / 5 new comments to your interpretation
- Username upvoted your interpretation / 12 people upvoted your interpretation
- Username upvoted your comment / 6 people upvoted your comment
- A moderator has removed your interpretation (we use moderator in this case for any user with permissions)
- A moderator has removed your comment (we use moderator in this case for any user with permissions)
- Your interpretation has been approved for SectionLabel on BookLabel
- Your comment has been approved for SectionLabel on BookLabel

Mentions
- You've been mentioned in a comment
- You've been added to BookLabel as an Editor/Moderator
- You've been removed from BookLabel as an Editor/Moderator

Open to suggestions as to when notifications get triggered, if instantly, or should we do it every X minutes? Do we bundle notifications (i.e. 5 new comments to your interpretation)?

When you click the notification, it should take you to the corresponding book, section page, or interpretation page.

**Comment by StoliarskyiKostiantyn** [comment]
Closed in #135
