### ISSUE TITLE
cut-out text

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#126]
<img width="2032" alt="text cut" src="https://github.com/Simple2B/open_law/assets/16442033/db7aeaae-8767-464e-b1be-4ab2e5b4a1dd">

<img width="2032" alt="Screenshot 2023-06-07 at 11 17 32" src="https://github.com/Simple2B/open_law/assets/16442033/f7d56351-8899-4367-936c-f00ee56befae">

**Comment by SvyatoslavArtymovych** [comment]
Done!
