### ISSUE TITLE
Add book versions

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#138]
You can find them in the figma file marked with green borders

Designs:

<img width="208" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/d31f09f1-fcda-4c09-a546-ad0ccf8eeac2">

<img width="769" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/17e2b44b-7315-42f2-a96e-17c6e1212898">

<img width="884" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/fffc0790-e1ab-42a9-9921-38f39a0f7bbd">

**Comment by StoliarskyiKostiantyn** [comment]
Done!
