### ISSUE TITLE
Change pop up trigger to when the user clicks on `connect wallet` and they don't have the extension + change copy

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#155]
Copy: You need an Ethereum-compatible wallet and browser extension to access this platform. 

We shouldn't recommend or redirect to any specific install link. 

<img width="326" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/44c7999f-d5dd-47f9-ba48-acf00e25f304">

**Comment by StoliarskyiKostiantyn** [comment]
Done!
