### ISSUE TITLE
fix approved-comments in book-view dropdown states

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#163]
The default state for approved-comments is collapsed—however, the icon + text shows as if it was expanded. Instead, it should look like state 2 (see pics below)

See the pictures below showing state 0 - collapsed but expanded icons, state 1 expanded with expanded icons, state 2 collapsed with collapsed icons

<img width="1623" alt="comments state 0" src="https://github.com/Simple2B/open_law/assets/16442033/854591e7-a8f7-4a52-a8df-7ccd931760d5">
<img width="1623" alt="comments state 1" src="https://github.com/Simple2B/open_law/assets/16442033/a506b782-f639-4f61-a649-ca41d8a1d1ed">
<img width="1623" alt="comments state 2" src="https://github.com/Simple2B/open_law/assets/16442033/10e61690-4c3b-4f73-9907-7f832c1ef7cb">

**Comment by StoliarskyiKostiantyn** [comment]
Fixed!
