### ISSUE TITLE
update comments icons to new one

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#166]
update in both book-label and interpretation components:
<img width="1623" alt="comments-icon-1" src="https://github.com/Simple2B/open_law/assets/16442033/09d642ab-b5a4-4cef-bad4-ecf7ec16e159">
<img width="1623" alt="comments-icon-2" src="https://github.com/Simple2B/open_law/assets/16442033/3e1879f3-3b13-452c-b0bb-12ee409bd549">

new icon:
<img width="149" alt="comments" src="https://github.com/Simple2B/open_law/assets/16442033/60b79430-aac7-4dcb-a675-3d19d03c0daa">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
