### ISSUE TITLE
change `no comments for current section` font to 14px and italic (same as empty collections/subcol)

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#169]
<img width="978" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/d025f003-c307-48b6-b94d-a88b6174a89f">

same as:

<img width="434" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/64ee203b-3931-4e8c-bd57-b6af6f2c24d6">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
