### ISSUE TITLE
make book-view collections and subcollections as markdown titles

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#170]
By adding # character for each nested level and between the last # and the text. Example (see source since github is markdown compatible and styles it):

# Collection
#### Subcollection lvl 3
...

<img width="978" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/18c6b45e-9d15-4ba9-afa9-fd380387030c">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
