### ISSUE TITLE
book-view styling

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#172]
Book label: keep bold, font size to 2rem
Tag: size .75rem
Add spacing between book label <> tags <> description
Collection label: remove underline and add divider instead, font-weight bold, size 1.5rem
Subcollection label: add font-weight bold
Section label: add underline

<img width="974" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/41c80acd-1565-460c-a2fa-6d9fad0254ac">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
