### ISSUE TITLE
book list component styling

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#175]
Book-label: font-weight bold, size 1rem
Book/version timestamp (last updated/created by): font-weight normal, size .875rem

<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/893f6a74-7b0e-4de3-8ecc-aca5a2e81f4e">
<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/79527d05-2993-44d5-9865-9f4736edf295">
<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/29481db4-a996-4421-be79-1ecbcdc5c7f6">
<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/31a78838-47ff-411c-8716-a31193a28a33">
<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/c6a1bd8c-0849-47be-8319-b387da776561">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
