### ISSUE TITLE
interpretations component styling (for all pages containing this component)

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#176]
- The last item of the breadcrumbs is slightly bigger than the others and bold, keep bold, change size same as others
- Section-label: font size to 1rem, add underline (made the same change in the issue for the book view)
- Interpretation-text: font size to 1rem
- Interpretation timestamp font size to .875rem

<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/830076fa-1982-481e-aaa2-6b29f498b9a8">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
