### ISSUE TITLE
interpretation-page changes

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#179]
remove `comment` title and dividir inside the editor
<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/467214a5-5f7c-47db-abe3-b84d63b1ab34">

move editor below `Comments:` and remove `:` from `Comments:` and add new comments icon issue#166 similar to section page ref: 
<img width="1623" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/57a6e1ac-27ba-4fb2-8d58-6c53bb43262c">

**Comment by SvyatoslavArtymovych** [comment]
Fixed!
