### ISSUE TITLE
update versions icon in book settings for consistency

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#193]
FROM
<img width="1621" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/8b404307-ceac-4bca-9acb-f23b16ca2950">

TO
<img width="195" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/7b7113c7-3260-4aa1-b1d6-64a3c1351ba8">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
