### ISSUE TITLE
mobile: change `submit` interpretation and `leave comment` buttons to be the same (prefer full width) 

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#195]
<img width="404" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/29630add-ed1c-4e9b-b8eb-a1b6488fb731">
<img width="410" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/fefc3756-5afd-4ca9-80bd-d46c962e4c77">

**Comment by StoliarskyiKostiantyn** [comment]
Done!
