### ISSUE TITLE
mobile: add home page title and description

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#196]
<img width="410" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/0bf53b0b-9730-4255-8e23-552763182387">

**Comment by StoliarskyiKostiantyn** [comment]
Done!

**Comment by monicazng** [comment]
@StoliarskyiKostiantyn it's not showing the page title and description for me in this page

**Comment by StoliarskyiKostiantyn** [comment]
Fixed!
