### ISSUE TITLE
mobile: home page scroll bug

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#197]
at: home page - latest interpretations
when I sort by: most upvoted / most recent, I can't scroll to the bottom of the page to see next pages (it starts bouncing and cuts out before the page numbers)

sort by most upvoted/ most recent
<img width="444" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/a4bdd36b-2216-4abc-a2d6-79d4837e5005">

sort by most comments
<img width="447" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/e2542c34-c8a5-456c-aa52-43c412f6458e">

**Comment by SvyatoslavArtymovych** [comment]
I added footer. Will close this issue after review
