### ISSUE TITLE
mobile: fix new book/sort buttons for my library, my contributions, and favorite books pages

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#198]
![IMG_8954](https://github.com/Simple2B/open_law/assets/16442033/19f62bfe-a374-4afe-9f67-aed4212532e6)
![IMG_8955](https://github.com/Simple2B/open_law/assets/16442033/309e8969-5d24-4df6-93da-572ae692cb04)
![IMG_8956](https://github.com/Simple2B/open_law/assets/16442033/32d121ef-d7e4-43a3-ac8d-66924467ee83)

**Comment by StoliarskyiKostiantyn** [comment]
Done!
