### ISSUE TITLE
mobile: move edit profile to last menu item below search

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#199]
![IMG_8957](https://github.com/Simple2B/open_law/assets/16442033/1b7a95e6-402a-4ff2-bb57-7e17d150ca25)

**Comment by anjali29singh** [comment]
can you assign this issue to  me ?

**Comment by monicazng** [comment]
> can you assign this issue to me ?

Hi @anjali29singh! Thanks for being willing to contribute; that's cool since we're just started :D We've got these issues covered since we're actively developing the platform internally but do star the repo and check in a couple of months!

**Comment by StoliarskyiKostiantyn** [comment]
Done!
