### ISSUE TITLE
mobile: my library shows less books than desktop 

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#212]
When I check monica's library from user profile on mobile, I see 3 books vs 5 books when I check monica's library from my-library page on desktop (see screenshots)

![mybooks](https://github.com/Simple2B/open_law/assets/16442033/618d4d3a-96a7-44dd-973f-e63df59b37e1)
<img width="1624" alt="mybooksdesktop" src="https://github.com/Simple2B/open_law/assets/16442033/7d0dc799-9c69-4ad0-b52f-dfff1bacfe1c">

**Comment by SvyatoslavArtymovych** [comment]
Fixed
