### ISSUE TITLE
New book - missing a way to create your first section or collection

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#66]
Since we've decided to use right-click to do all collection and section-related actions, we now don't have a way to create your first section or collection when you create your first book. 

<img width="1624" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/412e6651-2b7d-4493-b52b-e2269a65a5de">

Here are a couple of ideas:
1. Keep the [+] button next to settings to create collections or sections. Downside: it's useful when the table of contents (TOC) is empty, but it's confusing when we already have content in it since we will have to create + choose the location of the section or collection
2. Add a CTA on an empty TOC (see image below)

What are your thoughts? I think that (2) it's cleaner and consistent with other empty screens we have. 

<img width="633" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/a877d1f6-b4f7-439c-afd9-9f8429c1012d">

Another challenge is the situation when you create your first collection when a user has only created sections:

<img width="858" alt="image" src="https://github.com/Simple2B/open_law/assets/16442033/55e4edf9-0b24-4443-8436-1b49e7610b98">

Since we only allow either collections or sections and not both at the same level or hierarchy, it means that when a user creates their first collection, and they don't want to put all sections in that collection, they will actually have to create two collections. Do we have a way to resolve this at the moment? If not, we can think about something together.

**Comment by StoliarskyiKostiantyn** [comment]
Fixed
