### ISSUE TITLE
Add voting functionality to my own interpretations

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#94]
When I submit an interpretation, I cannot see the voting functionality. As a book owner or author of an interpretation or comment, I should be able to upvote/downvote my contributions. 

<img width="1456" alt="missing-voting-feature" src="https://github.com/Simple2B/open_law/assets/16442033/150b48f5-d226-43a5-8423-3f3942d70114">

**Comment by StoliarskyiKostiantyn** [comment]
Fixed!
