### ISSUE TITLE
Fix rename functionality

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#95]
1. When I rename a section or a collection, it shows a default `Section label` or `Collection label`. Instead, we should keep the current name so the user can edit on top of it instead of inserting a new one from scratch
2. When I press intro, it does not get renamed, seems to be broken

<img width="551" alt="rename" src="https://github.com/Simple2B/open_law/assets/16442033/ae35c414-6a09-41df-af94-39c096da3708">

**Comment by StoliarskyiKostiantyn** [comment]
Fiexed!
