### ISSUE TITLE
New section editor functionality?

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#96]
What's the current functionality of the `Editor` displayed when you create a `New Section`? 

We would like to use that area to submit the first interpretation if the user wants. But if it will add to our current timeline, we can just remove it and, like collection, only have a field for `Label` without about/editor.

<img width="734" alt="new-section-editor" src="https://github.com/Simple2B/open_law/assets/16442033/b14ea8cf-5e7d-4f15-8479-cc0f5616c252">

**Comment by StoliarskyiKostiantyn** [comment]
Done!
