### ISSUE TITLE
First item of breadcrumbs to `username` instead of `user-library`

### ISSUE THREAD

**Issue by monicazng** [logos-co/open-law#97]
<img width="653" alt="breadcrumbs" src="https://github.com/Simple2B/open_law/assets/16442033/0f4daf5d-080e-4a85-bdd4-58cc8ed136f5">

**Comment by StoliarskyiKostiantyn** [comment]
@monicazng Am I get it right:
My Books-> Me (and click linking to my_profile);
User's Books -> UserName;
And linking to profile.

**Comment by monicazng** [comment]
The way I imagine it:

Username > User's Book > Collection > Subcollection ...

**Comment by StoliarskyiKostiantyn** [comment]
Done!
